# write a program to print 100 random prime numbers 

#importing the required libraries
import random
import math


#---------------------Function-To-Find-Whether-The-Number-is-Prime-Or-Not-----------------------------------

def prime(n):
    x=0
    for i in range(2,math.sqrt(n)+1):
        if n%i==0:
            x=1
    if x==0:
        return n
    if x!=0:
        return 0


#---------------------Main-Program--------------------------------------------

#initalised a variable 'count' that holds the number of prime numbers printed
count=0

#A infinite loop which stops when the count becomes 100
# a variable 'a' that stores a random number generated by random Library
# checks if the n==prime(n) is True. It is only True when prime(n) returns n. 
#if True then print 'n' and increment the value of count
#check if value of count is 100 then break out the loop
while True:
    n=random.randint(1,1000)
    if n==prime(n):
        print(n)
        count=count+1
    if count==100:
        break
